[mgr]
show_hidden = true
sort_dir_first = true

[opener]
edit = [
  { run = "nvim %s", block = true, for = "unix" }
]

[open]
prepend_rules = [
  { url = "*.{py,js,ts,go,rs,c,cpp,h,sh,lua,json,yaml,yml,md,txt,toml}", use = "edit" },
]
